#!/bin/bash
DATA=`find . -name '*.shp'`
ogr2ogr -a_srs "+proj=tmerc +lat_0=0 +lon_0=60.05 +k=1 +x_0=1500000 +y_0=-5911057.63 +ellps=krass +towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 +units=m +no_defs" merge.shp
for i in $DATA
do
ogr2ogr -append -update merge.shp $i -f "Esri Shapefile"
done

