#!/bin/bash
mkdir TILED; for f in *.tif; do gdalwarp -s_srs "+proj=tmerc +lat_0=0 +lon_0=60.05 +k=1 +x_0=1500000 +y_0=-5911057.63 +ellps=krass +towgs84=23.92,-141.27,-80.9,-0,0.35,0.82,-0.12 +units=m +no_defs" -t_srs EPSG:2536 -of GTiff "$f" "temp.tif";gdal_translate -of GTIFF -co "TILED=YES"  "temp.tif" "TILED/${f%.tif}.tif" ;gdaladdo "TILED/${f%.tif}.tif" 2 4 8 16 32;rm temp.tif;done
